openapi: 3.0.0
info:
  title: API Ping finale
  version: 1.0.0
paths:
  /ping:
    get:
      summary: Vérifie si l'API fonctionne
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: "pong"