openapi: 3.0.3
info:
  title: Product Search API
  version: 1.0.0
  description: API de recherche de produits

paths:
  /products:
    get:
      summary: Recherche et liste des produits
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Liste de produits correspondant à la recherche
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  summary: Résultat avec plusieurs produits
                  value:
                    - name: "Pomme"
                      expiration_datetime: "2025-09-01T12:00:00Z"
                      price: 0.99
                    - name: "Banane"
                      expiration_datetime: "2025-08-30T18:30:00Z"
                      price: 1.20
                emptyResult:
                  summary: Résultat vide
                  value: []

components:
  parameters:
    limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        example: 10
      description: Nombre maximum d’éléments retournés
    q:
      name: q
      in: query
      required: false
      schema:
        type: string
        example: "fruit"
      description: Terme de recherche

  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: "Pomme"
        expiration_datetime:
          type: string
          format: date-time
          example: "2025-09-01T12:00:00Z"
        price:
          type: number
          format: float
          example: 0.99
      required:
        - name
        - expiration_datetime
        - price
